### ISSUE TITLE
[META] v3.2

### ISSUE THREAD

**Issue by lorepieri8** [AnyLedger/anyledger-wallet#114]
Rough overview of features/requirements for v3.2:

- HyperLedger Embedded side
  - [x] Use appropriate crypto functions to generate keys and transactions.
  - [x] Setup appropriate networking stack.

- HyperLedgerServer side: 
  - [x] Setup network and nodes (dockerfile + service on our dev VPS)
  - [x] https://github.com/hyperledger/sawtooth-supply-chain

**Comment by lorepieri8** [comment]
@pcppcp @randomshinichi 
Can this be closed?
