### ISSUE TITLE
[META] make ethereum's RPC using protobuf messages

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#140]
json is too verbose and too difficult to parse. We have to use binary format to pass data from embedded targets.

- [ ] evaluate available protobuf libraries suitable for an embedded system
- [ ] port JSONRPC messages to protobuf definition
- [ ] make a proxy that accepts protobuf-encoded message on one side (using HTTP as transport for now) and translates the request to JSONRPC (this can be done in python/flask)
- [ ] create protobuf RPC library for the embedded part
- [ ] integrate the proxy and the library
