### ISSUE TITLE
[META] v3.0

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#32]
Rough overview of features/requirements for v3.0:

- zephyr OS integration
  - [x] read some real world data from a hw sensor
  - [x] (optional) BLE connectivity

- ethereum
  - [x] transaction encoding and signing
  - [x] (optional) eth node CoAP proxy (for the demo we will use HTTP)
  - [x] web3-compatible library

- transport layer
  - ~~(easiest) CoAP over serial interface / console - requires a script on the other side (gateway)~~
  - ~~(possible) PPP (serial port) networking~~
  - (best) BLE 6LoWPAN  ✓

- gateway
  - [x] leshan
    - [x] device status 
  - [x] ethereum service
 
- visualize data stored on chain
   - [x] script that returns a formatted list of transactions for a given address

**Comment by lorepieri8** [comment]
Done!
