### ISSUE TITLE
[META] v3.1

### ISSUE THREAD

**Issue by lorepieri8** [AnyLedger/anyledger-wallet#99]
Rough overview of features/requirements for v3.1:

- Shell interface
   - [x] ~~create and delete accounts~~ postponed: it must be decided how will the accounts work
   - [x] display balance of the account
   - [x] transfer eth to another address
   - [x] check transaction status, get tx receipt

- Smart Contracts
   - [x] make it possible to execute smart contract method
   - [x] ERC20 Support

**Comment by devtodev** [comment]
Hi! Would someone share me where I can start to research to use and implement the shell interface? Is a complete new implementation? Do we have some example or tutorial?

**Comment by lorepieri8** [comment]
@pcppcp is working on it.

https://gist.github.com/pcppcp/2f30c50858cb4093242dcbb52e9992c8

**Comment by pcppcp** [comment]
Hi @devtodev 
if you manage to build the qemu target then you'll be able to interact with the shell.
The submodules sources are in the `zephyr` directory, i.e. for the wallet it's `zephyr/wallet.c`.
